export const NEW_CART_REQUEST = "NEW_CART_REQUEST";
export const NEW_CART_SUCCESS = "NEW_CART_SUCCESS";
export const NEW_CART_RESET = "NEW_CART_RESET";
export const NEW_CART_FAIL = "NEW_CART_FAIL";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_RESET = "UPDATE_CART_RESET";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_RESET = "DELETE_CART_RESET";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";

export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_SUCCESS = "CART_DETAILS_SUCCESS";
export const CART_DETAILS_FAIL = "CART_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_RESET = "REMOVE_CART_ITEM_RESET";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

//Local
export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
