export const NEW_WISHLIST_REQUEST = "NEW_WISHLIST_REQUEST";
export const NEW_WISHLIST_SUCCESS = "NEW_WISHLIST_SUCCESS";
export const NEW_WISHLIST_RESET = "NEW_WISHLIST_RESET";
export const NEW_WISHLIST_FAIL = "NEW_WISHLIST_FAIL";

export const UPDATE_WISHLIST_REQUEST = "UPDATE_WISHLIST_REQUEST";
export const UPDATE_WISHLIST_SUCCESS = "UPDATE_WISHLIST_SUCCESS";
export const UPDATE_WISHLIST_RESET = "UPDATE_WISHLIST_RESET";
export const UPDATE_WISHLIST_FAIL = "UPDATE_WISHLIST_FAIL";

export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_RESET = "DELETE_WISHLIST_RESET";
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";

export const WISHLIST_DETAILS_REQUEST = "WISHLIST_DETAILS_REQUEST";
export const WISHLIST_DETAILS_SUCCESS = "WISHLIST_DETAILS_SUCCESS";
export const WISHLIST_DETAILS_FAIL = "WISHLIST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_RESET = "ADD_TO_WISHLIST_RESET";
export const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";

export const REMOVE_WISHLIST_ITEM_REQUEST = "REMOVE_WISHLIST_ITEM_REQUEST";
export const REMOVE_WISHLIST_ITEM_SUCCESS = "REMOVE_WISHLIST_ITEM_SUCCESS";
export const REMOVE_WISHLIST_ITEM_RESET = "REMOVE_WISHLIST_ITEM_RESET";
export const REMOVE_WISHLIST_ITEM_FAIL = "REMOVE_WISHLIST_ITEM_FAIL";

//Local
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const REMOVE_WISHLIST_ITEM = "REMOVE_WISHLIST_ITEM";
